# Generated by Django 4.0.1 on 2022-01-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookId', models.AutoField(primary_key=True, serialize=False)),
                ('BookTitle', models.CharField(max_length=100)),
                ('BookCategorie', models.CharField(max_length=100)),
                ('BookAuthor', models.CharField(max_length=100)),
                ('BookPrice', models.CharField(max_length=100)),
                ('BookPhoto', models.CharField(max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('CategorieId', models.AutoField(primary_key=True, serialize=False)),
                ('CategorieType', models.CharField(max_length=100)),
            ],
        ),
    ]
